package com.example.android_native_example

import com.vppos.nfc.core.NfcScanResult
import com.vppos.nfc.core.utils.NfcCoreErrorPayload
import org.json.JSONArray
import org.json.JSONObject

/** A request issued by the web package through @webview-bridge/react-native. */
internal data class EcertBridgeRequest(
    val bridgeId: String,
    val eventId: String,
    val method: String,
    val args: JSONArray,
)

internal sealed interface EcertBridgeMessage {
    data class Request(val request: EcertBridgeRequest) : EcertBridgeMessage
    data class StateRequested(val bridgeId: String) : EcertBridgeMessage
}

/**
 * Compatibility adapter for the React Native WebView protocol used by eCert.
 *
 * Android's [android.webkit.WebView] has no `ReactNativeWebView` object. The
 * document-start script provides that object and sends messages to the
 * origin-restricted WebMessageListener. Replies are sent through the exact
 * event emitter and bridge id generated by @webview-bridge/web.
 */
internal object EcertBridgeContract {
    const val BRIDGE_OBJECT_NAME = "WebViewBridge"
    private const val BRIDGE_TYPE = "bridge"
    private const val GET_BRIDGE_STATE_TYPE = "getBridgeState"

    private val supportedMethods = listOf(
        "getSystemInfo",
        "openNFC",
        "requestCameraPermission",
    )

    fun documentStartScript(): String = """
        (function() {
            window.__bridgeMethods__ = ${JSONArray(supportedMethods)};
            window.__bridgeInitialState__ = {};
            window.ReactNativeWebView = window.ReactNativeWebView || {};
            window.ReactNativeWebView.postMessage = function(message) {
                if (window.$BRIDGE_OBJECT_NAME &&
                    typeof window.$BRIDGE_OBJECT_NAME.postMessage === "function") {
                    window.$BRIDGE_OBJECT_NAME.postMessage(String(message));
                }
            };
        })();
        true;
    """.trimIndent()

    fun parseMessage(rawMessage: String): EcertBridgeMessage? = runCatching {
        val root = JSONObject(rawMessage)
        val bridgeId = root.optString("bridgeId").trim()
        if (bridgeId.isBlank()) return null

        when (root.optString("type").trim()) {
            BRIDGE_TYPE -> {
                val body = root.optJSONObject("body") ?: return null
                val eventId = body.optString("eventId").trim()
                val method = body.optString("method").trim()
                if (eventId.isBlank() || method.isBlank()) return null

                EcertBridgeMessage.Request(
                    EcertBridgeRequest(
                        bridgeId = bridgeId,
                        eventId = eventId,
                        method = method,
                        args = body.optJSONArray("args") ?: JSONArray(),
                    ),
                )
            }

            GET_BRIDGE_STATE_TYPE -> EcertBridgeMessage.StateRequested(bridgeId)
            else -> null
        }
    }.getOrNull()

    fun success(data: Any?): JSONObject = methodResult(
        status = "success",
        data = data,
        error = null,
    )

    fun failure(error: NfcCoreErrorPayload): JSONObject = methodResult(
        status = "failed",
        data = null,
        error = error.toJson(),
    )

    fun cancelled(error: NfcCoreErrorPayload): JSONObject = methodResult(
        status = "cancelled",
        data = null,
        error = error.toJson(),
    )

    fun nativeMethodResultScript(request: EcertBridgeRequest, result: JSONObject): String =
        nativeEmitterScript(
            bridgeId = request.bridgeId,
            eventName = "${request.method}-${request.eventId}",
            data = result,
        )

    fun bridgeStateScript(bridgeId: String): String = nativeEmitterScript(
        bridgeId = bridgeId,
        eventName = "bridgeStateChange",
        data = JSONObject(),
    )

    fun nfcData(result: NfcScanResult): JSONObject = JSONObject()
        .put("citizenId", result.citizenId)
        .put("fullName", result.fullName)
        .put("dob", result.dob)
        .put("gender", result.gender)
        .put("nationality", result.nationality)
        .put("permanentAddress", result.permanentAddress)
        .put("issueDate", result.issueDate)
        .put("expireDate", result.expireDate)
        .put("issuePlace", result.issuePlace)
        .put("imageFace", result.imageFace)
        .put("imageFromChip", result.imageFromChip)
        .put("liveFaceImage", result.liveFaceImage)
        .put("frontCardFileId", result.frontCardFileId)
        .put("backCardFileId", result.backCardFileId)
        .put("dg1DataB64", result.dg1DataB64)
        .put("dg2DataB64", result.dg2DataB64)
        .put("dg13DataB64", result.dg13DataB64)
        .put("dg14DataB64", result.dg14DataB64)
        .put("sodData", result.sodData)
        .put("passiveAuth", result.passiveAuth)
        .put("chipAuth", result.chipAuth)

    private fun methodResult(status: String, data: Any?, error: Any?): JSONObject = JSONObject()
        .put("status", status)
        .put("data", data)
        .put("error", error)

    private fun NfcCoreErrorPayload.toJson(): JSONObject = JSONObject()
        .put("code", code)
        .put("message", message)

    private fun nativeEmitterScript(bridgeId: String, eventName: String, data: Any?): String {
        val bridgeIdJson = JSONObject.quote(bridgeId)
        val eventNameJson = JSONObject.quote(eventName)
        val dataJson = when (data) {
            null, JSONObject.NULL -> "null"
            is JSONObject, is JSONArray -> data.toString()
            is String -> JSONObject.quote(data)
            is Number, is Boolean -> data.toString()
            else -> JSONObject.quote(data.toString())
        }

        return """
            (function() {
                var bridgeId = $bridgeIdJson;
                var eventName = $eventNameJson;
                var data = $dataJson;
                var emitter = window.nativeEmitterMap && window.nativeEmitterMap[bridgeId];
                if (emitter && typeof emitter.emit === "function") {
                    emitter.emit(eventName, data);
                } else if (window.nativeEmitter && typeof window.nativeEmitter.emit === "function") {
                    window.nativeEmitter.emit(eventName, data);
                } else {
                    window.nativeBatchedEvents = window.nativeBatchedEvents || [];
                    window.nativeBatchedEvents.push([eventName, data]);
                }
                return true;
            })();
        """.trimIndent()
    }
}
